version: "3.9"
services:
  ai_api:
    build: ./AI.API
    container_name: ai_api
    ports:
      - "8000:8000"

  backend:
    build: ./server
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - ai_api
    environment:
      AI_API_URL: "http://ai_api:8000/chat"
    volumes:
      - C:\Users\marou\.m2:/root/.m2

  frontend:
    build: ./client.web
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
